#%RAML 1.0 NamedExample
value:

  - 
    usItemId: 1 
    item_name: Colgate Maxfresh Toothpaste
    item_type: Teeth Care
    item_mrp: 120
    item_return: false
    
  - 
    usItemId: 2 
    item_name: Pepsodant Maxfresh Toothpaste
    item_type: Teeth Care
    item_mrp: 125
    item_return: false
