#%RAML 1.0 NamedExample

productDescription: Get pearly white teeth with this Pepsodent 2 in 1 Toothpaste. It helps fight tooth cavities and decay with the specially designed formula of this toothpaste. The protective elements in this toothpaste help prevent plaque formation and gum sensitivity. 
