#%RAML 1.0 NamedExample

CustomerReviews: [
 {
  name: Sachin,
  star_rating: 4.25 ,
  title: Good Product,
  description: Very good product
  },{
  name: Vivek,
  star_rating: 4.25 ,
  title: Good Product,
  description: Very good product
}
]
average_rating: 4.25